apiVersion: v1
kind: Namespace
metadata:
  name: pubsub
  labels:
    name: pubsub
---

apiVersion: v1
kind: Namespace
metadata:
  name: bq
  labels:
    name: bq
---

apiVersion: v1
kind: Namespace
metadata:
  name: api-gateway
  labels:
    name: api-gateway

